[package]
name = "grandpa-verifier-primitives"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
# crates.io
anyhow = { workspace = true }
finality-grandpa = { version = "0.16.0", features = ["derive-codec"], default-features = false }
codec = { workspace = true }
log = { workspace = true }

# substrate
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }
frame-support = { workspace = true }
sp-std = { workspace = true }
sp-trie = { workspace = true }
sp-storage = { workspace = true }
sp-consensus-grandpa = { workspace = true }
# polytope
ismp = { workspace = true }


[features]
default = ["std"]
std = [
    "anyhow/std",
    "sp-storage/std",
    "finality-grandpa/std",
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-io/std",
    "frame-support/std",
    "sp-consensus-grandpa/std",
    "sp-std/std",
    "sp-trie/std",
    "ismp/std",
]
